Ajax rails
MiKaMoRe/QnA pull request #7
Opened 2021-08-23 20:24 UTC by MiKaMoRe

2021-08-25 04:22 UTC, VidgarVii commented on app/models/answer.rb
> +    !best_of.nil?
можно написать так
best.presents?

2021-08-25 04:22 UTC, VidgarVii commented on app/models/answer.rb
> +  has_one :best_of, foreign_key: 'best_answer_id', class_name: 'Question', dependent: :nullify
для определения лучший ответ или нет достоточно добавить в таблицу булевое поле best
связь с вопросом у нас и так есть. Знать вопросу кто у него лучший ответ можно через простой sql запрос без ассоциаций

2021-08-25 04:24 UTC, VidgarVii requested changes

2021-08-25 04:24 UTC, VidgarVii commented on app/controllers/answers_controller.rb
> +  def nominate
этот экшен надо протестировать

2021-08-25 04:24 UTC, VidgarVii commented on app/models/answer.rb
> +  end
методы не протестированы

2021-08-26 13:55 UTC, vkurennov requested changes

2021-08-27 09:21 UTC, vkurennov requested changes

2021-08-28 09:01 UTC, vkurennov requested changes

2021-08-28 09:01 UTC, vkurennov commented on app/models/question.rb
> +      if best_answer
замени на постфиксный if

2021-08-28 09:01 UTC, vkurennov commented on app/models/question.rb
> +  def new_best_answer(answer)
перенеси в модель ответа, ты здесь работаешь только с ответами, так почему за это отвечает модель вопроса? нарушение принципа единственной ответсвенности

2021-08-28 15:06 UTC, merged